spring:
  application:
    name: release-intelligence

  datasource:
    url: jdbc:postgresql://localhost:5432/release_intelligence
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080